### ISSUE TITLE
A3C Doom: Delayed convergence  

### ISSUE THREAD

**Issue by IbrahimSobh** [awjuliani/DeepRL-Agents#15]
I faced delayed convergence in second run, is there an explanation? 

First Run: (around 200 and smooth)

![doom_basic_reward](https://cloud.githubusercontent.com/assets/19908396/23826651/657a94fc-06a9-11e7-825b-0d59015f61bb.PNG)

Second Run:  (around 300 and sudden) 

![doom_basic_reward_2](https://cloud.githubusercontent.com/assets/19908396/23826654/6d4dab9c-06a9-11e7-859e-fc6909a8d5a9.PNG)

**Comment by awjuliani** [comment]
Hi Ibrahim,

One reason for this is the different variable initializations when we set up the network. Another is simply the randomness inherent in action selection and randomness in the environment itself. These two differences are relatively minor in a large scale.
