### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nanxintin** [awjuliani/DeepRL-Agents#3]
Hi,
I has read your blogs about the RL and like it very much.
When I tried to run the A3C-Doom, I came across the  Segmentation fault (core dumped) error after the terminal output starting workers .
My computer has 32G memory,and two E5 CPUs.
The error troubles me a lot and I wounder if you can give me some advice.
Thanks.

**Comment by awjuliani** [comment]
I'm sorry you are having that issue. Can you give me the exact error output that is related to the segmentation fault?

**Comment by nanxintin** [comment]
@awjuliani Thank you for your reply. What is strange is that when I run the code in my virtual machine, everything goes well. And running in the E5 computer, segmentation fault (core dumped) error happened again. Maybe I need to check my computer first.
BTW, I think using the .cfg file in the code is more concise and easy to compare with other's work. 
Thanks again.

**Comment by reaIws** [comment]
@nanxintin are you resolve this problem ？ i meet the same error, can you help me ? best congratulate for you

**Comment by nanxintin** [comment]
@reaIws I just change a machine and run the code successfully. To be honest, I didn't figure out this error.

**Comment by reaIws** [comment]
@nanxintin oh,thanks for you ,i get some replay from here(https://github.com/mwydmuch/ViZDoom/issues/271)
