### ISSUE TITLE
Model-Network occasionally outputs unreasonably big mean reward

### ISSUE THREAD

**Issue by kkjh0723** [awjuliani/DeepRL-Agents#6]
I copy your code in a python file and run the simulation several time.
Usually it works fine, but occasionally the mean reward become very large.
Below is the copy of the output log that you made

     World Perf: Episode 247.000000. Reward 35.333333. action: 0.000000. mean reward 35.000038.
     World Perf: Episode 250.000000. Reward 29.333333. action: 1.000000. mean reward 34.979885.
     World Perf: Episode 253.000000. Reward 39.666667. action: 0.000000. mean reward 34.893707.
     World Perf: Episode 256.000000. Reward 21.000000. action: 1.000000. mean reward 34.590328.
     World Perf: Episode 259.000000. Reward 62.333333. action: 0.000000. mean reward 34.643253.
     World Perf: Episode 262.000000. Reward 40.666667. action: 1.000000. mean reward 34.418655.
     World Perf: Episode 265.000000. Reward 31.000000. action: 1.000000. mean reward 34.128536.
     World Perf: Episode 268.000000. Reward 25.000000. action: 1.000000. mean reward 3763953194369116274688.000000.
     World Perf: Episode 271.000000. Reward 50.333333. action: 0.000000. mean reward 3689050732741573738496.000000.
     World Perf: Episode 274.000000. Reward 20.333333. action: 0.000000. mean reward 3615638681115714125824.000000.
     World Perf: Episode 277.000000. Reward 26.666667. action: 1.000000. mean reward 3543687766093959528448.000000.
     World Perf: Episode 280.000000. Reward 44.000000. action: 0.000000. mean reward 3473168432803755327488.000000.
     World Perf: Episode 283.000000. Reward 19.000000. action: 1.000000. mean reward 3404052533747430457344.000000.
     World Perf: Episode 286.000000. Reward 59.666667. action: 1.000000. mean reward 3336311921427313852416.000000.

It seems that the predicted reward of the Model sometimes become too large.
Do you know what is the problem?
Is it just some cases that the model failed to learn?

**Comment by awjuliani** [comment]
This is likely due to the model failing to predict a failure state in the episode. In such a case the model runs a simulated episode for millions of steps because it believes it is still succeeding. Tuning the `done` predictor is definitely the trickiest part of the model. I would suggest adjusting the model parameters to make it more liberal in predicting a failure state. Of course, it is a fine balance.

**Comment by kkjh0723** [comment]
Thanks for the answer and suggestion. Now I understood what happens exactly.
