### ISSUE TITLE
self.indexes in vanllina policy gradient

### ISSUE THREAD

**Issue by hassaanhashmi** [awjuliani/DeepRL-Agents#60]
Hi,
I have been trying to make sense of the self.indexes line but after spending a whole day, I am still clueless. I would appreciate if anyone could help me understand this particular line.

**Comment by abadhikari** [comment]
Hi MHHashmi,
Did you ever end up figuring out the indexes variable?

**Comment by hassaanhashmi** [comment]
Hi abadhikari,
Nope, still haven't been able to do that.
