### ISSUE TITLE
Running A3C-Doom.ipynb on Tensorflor 1.0.0+ and BasicLSTMCell

### ISSUE THREAD

**Issue by DMTSource** [awjuliani/DeepRL-Agents#7]
Great tutorial!

If you are recently installing from pip Tensorflow is now 1.0.0+. In order to run the tutorial you will need to update:

`tf.nn.rnn_cell.BasicLSTMCell`
to:
`tf.contrib.rnn.BasicLSTMCell`

**Comment by awjuliani** [comment]
Thanks for pointing this out! I've gone though the repo today and updated all the notebooks to be TF1.0 compatible.
