### ISSUE TITLE
slim?

### ISSUE THREAD

**Issue by MarkFuini** [awjuliani/DeepRL-Agents#9]
Vanilla-Policy.ipynb

I am getting this when trying to run.  I guess I didn't get a dependency?

Traceback (most recent call last):
  File "agent2.py", line 68, in <module>
    myAgent = agent(lr=1e-2,s_size=5,a_size=3,h_size=10) #Load the agent.
  File "agent2.py", line 41, in __init__
    hidden = slim.fully_connected(self.state_in,h_size,biases_initializer=None,activation_fn=tf.nn.relu)
NameError: global name 'slim' is not defined

**Comment by awjuliani** [comment]
`slim` refers to Tensorflow Slim, https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim . It is an easier way of defining layers using Tensorflow. Are you using the latest version of Tensorflow?

**Comment by MarkFuini** [comment]
Hi,

That simple import in the slim page worked.

Thanks again!
